"""Constants used throughout the application."""

THREAD_UPDATE_INTERVAL = 0.2
CRAZYFLIE_DISTANCE_ERROR_DELTA = 0.01
CRAZYFLIE_HEADING_ERROR_DELTA = 0.01
CRAZYFLIE_CONTOL_LOOPS_MAX_ITER = 100
CRAZYFLIE_TAKEOFF_ALTITUDE = 0.30
CRAZYFLIE_POSITION_HL_COMMANDER_DEFAULT_VELOCITY = 0.20
CRAZYFLIE_POSITION_HL_COMMANDER_DEFAULT_HEIGHT = 0.20